steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--tag=_DKR_IMAGE',
           '-f',
           'Dockerfile',
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '_DKR_IMAGE']


  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy',
           'robo9-api-server',
           '--image=_DKR_IMAGE',
           '--region',
           '$_REGION',
           '--platform',
           'managed',
           '--service-account=$_SRV_ACCT',
           '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY